dist: xenial
sudo: required
language: python
python:
  - "3.5"
  - "3.6"

notifications:
  email: true

# command to install dependencies
install:
  - pip install colcon-common-extensions flake8 pytest PyYAML argparse
  - curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
  - sudo apt -qq update
  - sudo apt -qq install ros-ardent-ament-index-python ros-ardent-ament-cmake ros-ardent-ament-lint-auto ros-ardent-ament-cmake-pytest

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  # prepare workspace
  - source /opt/ros/ardent/setup.bash
  - mkdir -p ros_ws/src && ln -s $TRAVIS_BUILD_DIR ros_ws/src && cd ros_ws

# command to run tests
script:
  - colcon build
  - colcon test && colcon test-result
